actions:
  backup:
    type: Deployment
    outputArtifacts:
      mysqlCloudDump:
        keyValue:
          path: '/mysql-backups/{{ .Deployment.Namespace }}/{{ .Deployment.Name }}/{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time  | date "2006-01-02T15-04-05" }}/dump.sql.gz'
    phases:
    - func: KubeExec
      name: dumpToObjectStore
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: kanister-sidecar
        cmd:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            s3_path="s3://${S3_BUCKET}{{ .ArtifactsOut.mysqlCloudDump.KeyValue.path }}"
            s3_cmd=(aws "${S3_VERIFY_SSL}")
            if [[ -n "${S3_ENDPOINT+set}" ]]
            then
                s3_cmd+=(--endpoint "${S3_ENDPOINT}")
            fi
            s3_cmd+=(s3 cp - "${s3_path}")
            mysqldump -u root --password="${MYSQL_ROOT_PASSWORD}" --single-transaction --all-databases | gzip - | ${s3_cmd[@]}
  restore:
    type: Deployment
    inputArtifactNames:
      - mysqlCloudDump
    phases:
    - func: KubeExec
      name: restoreFromBlobStore
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: kanister-sidecar
        cmd:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            s3_path="s3://${S3_BUCKET}{{ .ArtifactsIn.mysqlCloudDump.KeyValue.path }}"
            s3_cmd=(aws "${S3_VERIFY_SSL}")
            if [[ -n "${S3_ENDPOINT+set}" ]]
            then
                s3_cmd+=(--endpoint "${S3_ENDPOINT}")
            fi
            s3_cmd+=(s3 cp "${s3_path}" -)
            ${s3_cmd[@]} | gunzip -c - | mysql -u root --password="${MYSQL_ROOT_PASSWORD}"
  delete:
    type: Deployment
    inputArtifactNames:
      - mysqlCloudDump
    phases:
    - func: KubeExec
      name: deleteFromBlobStore
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: kanister-sidecar
        cmd:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            s3_path="s3://${S3_BUCKET}{{ .ArtifactsIn.mysqlCloudDump.KeyValue.path }}"
            s3_cmd=(aws "${S3_VERIFY_SSL}")
            if [[ -n "${S3_ENDPOINT+set}" ]]
            then
                s3_cmd+=(--endpoint "${S3_ENDPOINT}")
            fi
            s3_cmd+=(s3 rm "${s3_path}")
            ${s3_cmd[@]}

