actions:
  backup:
    type: Deployment
    outputArtifacts:
      mysqlCloudDump:
        keyValue:
          path: '/mysql-backups/{{ .Deployment.Namespace }}/{{ .Deployment.Name }}/{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time  | date "2006-01-02T15-04-05" }}/dump.sql.gz'
    phases:
    - func: KubeExec
      name: dumpToObjectStore
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: kanister-sidecar
        command:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            s3_path="/mysql-backups/{{ .Deployment.Namespace }}/{{ .Deployment.Name }}/{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time  | date "2006-01-02T15-04-05" }}/dump.sql.gz"
            mysqldump --column-statistics=0 -h 127.0.0.1 -u root --password="${MYSQL_ROOT_PASSWORD}" --single-transaction --all-databases | gzip - | kando location push --profile '{{ toJson .Profile }}' --path ${s3_path} -
  restore:
    type: Deployment
    inputArtifactNames:
      - mysqlCloudDump
    phases:
    - func: KubeExec
      name: restoreFromBlobStore
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: kanister-sidecar
        command:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            s3_path="{{ .ArtifactsIn.mysqlCloudDump.KeyValue.path }}"
            kando location pull --profile '{{ toJson .Profile }}' --path ${s3_path} - | gunzip | mysql -h 127.0.0.1 -u root --password="${MYSQL_ROOT_PASSWORD}"
  delete:
    type: Namespace
    inputArtifactNames:
      - mysqlCloudDump
    phases:
    - func: KubeTask
      name: deleteFromBlobStore
      args:
        namespace: "{{ .Namespace.Name }}"
        image: kanisterio/kanister-tools:0.29.0
        command:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            s3_path="{{ .ArtifactsIn.mysqlCloudDump.KeyValue.path }}"
            kando location delete --profile '{{ toJson .Profile }}' --path ${s3_path}
