apiVersion: v1
description: A helm chart to create profile custom resource for kanister
engine: gotpl
name: profile
home: https://kanister.io/
version: 0.110.0
maintainers:
  - email: tom@kasten.io
    name: tdmanv
  - email: ilya@kasten.io
    name: depohmel
icon: https://kasten.io/assets/img/kanister-logo.png
appVersion: 0.1.0
source: https://github.com/kanisterio/kanister
