description: MySQL w/ Kanister support based on stable/mysql
engine: gotpl
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
keywords:
- mysql
- database
- sql
- kanister
maintainers:
- email: tom@kasten.io
  name: tdmanv
name: kanister-mysql
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/mysql
- https://kanister.io/
version: 0.26.0
appVersion: 5.7.14
