name: kanister-mongodb-replicaset
home: https://github.com/mongodb/mongo
version: 0.25.0
appVersion: 3.6
description: Kanister-enabled NoSQL document-oriented database that stores JSON-like documents with
  dynamic schemas, simplifying the integration of data in content-driven applications.
icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
sources:
  - https://github.com/mongodb/mongo
  - https://github.com/percona/mongodb_exporter
maintainers:
  - email: tom@kasten.io
    name: tdmanv
  - email: ilya@kasten.io
    name: depohmel
