apiVersion: v1
name: kanister-elasticsearch
home: https://www.elastic.co/products/elasticsearch
version: 0.22.0
appVersion: 6.3.1
description: Elasticsearch w/ Kanister support based on incubator/elasticsearch
icon: https://static-www.elastic.co/assets/blteb1c97719574938d/logo-elastic-elasticsearch-lt.svg
sources:
- https://github.com/kansiterio/kanister
- https://www.elastic.co/products/elasticsearch
- https://github.com/jetstack/elasticsearch-pet
- https://github.com/giantswarm/kubernetes-elastic-stack
- https://github.com/GoogleCloudPlatform/elasticsearch-docker
- https://github.com/clockworksoul/helm-elasticsearch
- https://github.com/pires/kubernetes-elasticsearch-cluster
maintainers:
- name: tdmanv
  email: tom@kasten.io
- name: depohmel
  email: ilya@kasten.io
- name: SupriyaKasten
  email: supriya@kasten.io
