apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "local-registry.fullname" . }}
  labels:
    app: {{ include "local-registry.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "local-registry.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "local-registry.name" . }}
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: storage
              mountPath: /var/lib/registry
      volumes:
        - name: storage
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "local-registry.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
