apiVersion: v1
kind: Service
metadata:
  name: {{ include "local-registry.fullname" . }}
spec:
  selector:
    app: {{ include "local-registry.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
