name: kanister

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  make-docs:
    name: Make docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Make Docs
        run: make docs
  
  kind-test:
    name: Kind test
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@master
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008
      - name: Go Setup
        uses: actions/setup-go@v2.1.3
      - name: Docker Pull
        run: docker pull kindest/node:v1.18.2
      - name: Go Mod Download
        run: make go-mod-download
      - name: Start Kind
        run: make start-kind
      - name: Make Build
        run: make build
      - name: Make Test
        run: make test
      - name: Stop Kind
        run: make stop-kind
  
  minio-test:
    name: Minio Test
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@master
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008
      - name: Go Setup
        uses: actions/setup-go@v2.1.3
      - name: Go Mod Download
        run: make go-mod-download
      - name: Docker Pull
        run: docker pull kindest/node:v1.18.2
      - name: Start Kind
        run: make start-kind
      - name: Install Minio
        run: make install-minio
      - name: Run integration test
        run: make integration-test
      - name: Stop Kind
        run: make stop-kind

  lint:
    name: Lint phase
    runs-on: ubuntu-latest
    steps:
      - name: Go-linter
        uses: Jerome1337/golint-action@v1.0.2
